/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param eventKey 
 * @param hookUrl 
 * @param key 
 * @param status 
 */
@Serializable
data class RestHook (
    @SerialName("eventKey") @Optional val eventKey: String? = null,
    @SerialName("hookUrl") @Optional val hookUrl: String? = null,
    @SerialName("key") @Optional val key: String? = null,
    @SerialName("status") @Optional val status: RestHook.Status? = null
) {

    /**
    * 
    * Values: UNVERIFIED,VERIFIED,INACTIVE
    */
    @Serializable(with = Status.Serializer::class)
    enum class Status(val value: String){
    
        UNVERIFIED("Unverified"),
    
        VERIFIED("Verified"),
    
        INACTIVE("Inactive");
    

      class Serializer: EnumStringSerializer<Status>(Status::class)

      override fun toString(): String = value.toString()
    }

}

