/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param first_name 
 * @param id 
 * @param last_name 
 */
@Serializable
data class SimpleUser (
    @SerialName("first_name") @Optional val firstName: String? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("last_name") @Optional val lastName: String? = null
) {

}

