/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.ContactAddress

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * Information about the company that owns/uses this account
 * @param address 
 * @param business_goals The goals of this business, ie. Grow Business, Convert more leads
 * @param business_primary_color 
 * @param business_secondary_color 
 * @param business_type The type of business
 * @param currency_code 
 * @param email 
 * @param language_tag 
 * @param logo_url 
 * @param name 
 * @param phone 
 * @param phone_ext 
 * @param time_zone 
 * @param website 
 */
@Serializable
data class AccountProfile (
    @SerialName("address") @Optional val address: ContactAddress? = null,
    /* The goals of this business, ie. Grow Business, Convert more leads */
    @SerialName("business_goals") @Optional val businessGoals: List<String>? = null,
    @SerialName("business_primary_color") @Optional val businessPrimaryColor: String? = null,
    @SerialName("business_secondary_color") @Optional val businessSecondaryColor: String? = null,
    /* The type of business */
    @SerialName("business_type") @Optional val businessType: String? = null,
    @SerialName("currency_code") @Optional val currencyCode: String? = null,
    @SerialName("email") @Optional val email: String? = null,
    @SerialName("language_tag") @Optional val languageTag: String? = null,
    @SerialName("logo_url") @Optional val logoUrl: String? = null,
    @SerialName("name") @Optional val name: String? = null,
    @SerialName("phone") @Optional val phone: String? = null,
    @SerialName("phone_ext") @Optional val phoneExt: String? = null,
    @SerialName("time_zone") @Optional val timeZone: String? = null,
    @SerialName("website") @Optional val website: String? = null
) {

}

