/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param contact_id Required for pop-up reminders
 * @param description 
 * @param end_date 
 * @param location 
 * @param remind_time Value in minutes before start_date to show pop-up reminder.  Acceptable values are [5,10,15,30,60,120,240,480,1440,2880]
 * @param start_date 
 * @param title 
 * @param user Required only for pop-up reminders
 */
@Serializable
data class Appointment (
    @SerialName("end_date") val endDate: String,
    @SerialName("start_date") val startDate: String,
    @SerialName("title") val title: String,
    /* Required for pop-up reminders */
    @SerialName("contact_id") @Optional val contactId: Long? = null,
    @SerialName("description") @Optional val description: String? = null,
    @SerialName("location") @Optional val location: String? = null,
    /* Value in minutes before start_date to show pop-up reminder.  Acceptable values are [5,10,15,30,60,120,240,480,1440,2880] */
    @SerialName("remind_time") @Optional val remindTime: Int? = null,
    /* Required only for pop-up reminders */
    @SerialName("user") @Optional val user: Long? = null
) {

}

