/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.Goal
import io.mverse.client.infusionsoft.models.Sequence

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param active_contact_count 
 * @param completed_contact_count 
 * @param created_by_global_id 
 * @param date_created 
 * @param error_message 
 * @param goals 
 * @param id 
 * @param locked 
 * @param name 
 * @param published_date 
 * @param published_status 
 * @param published_time_zone 
 * @param sequences 
 * @param time_zone 
 */
//@Serializable Not using right now
data class Campaign (
    @SerialName("active_contact_count") @Optional val activeContactCount: Int? = null,
    @SerialName("completed_contact_count") @Optional val completedContactCount: Int? = null,
    @SerialName("created_by_global_id") @Optional val createdByGlobalId: Long? = null,
    @SerialName("date_created") @Optional val dateCreated: java.time.LocalDateTime? = null,
    @SerialName("error_message") @Optional val errorMessage: String? = null,
    @SerialName("goals") @Optional val goals: List<Goal>? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("locked") @Optional val locked: Boolean? = null,
    @SerialName("name") @Optional val name: String? = null,
    @SerialName("published_date") @Optional val publishedDate: java.time.LocalDateTime? = null,
    @SerialName("published_status") @Optional val publishedStatus: Boolean? = null,
    @SerialName("published_time_zone") @Optional val publishedTimeZone: String? = null,
    @SerialName("sequences") @Optional val sequences: List<Sequence>? = null,
    @SerialName("time_zone") @Optional val timeZone: String? = null
) {

}

