/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param formId 
 * @param id 
 * @param landingPageId 
 * @param leadBucketIds 
 * @param name 
 * @param properties 
 * @param ready 
 * @param type 
 */
@Serializable
data class CampaignLandingPageNodeDTO (
    @SerialName("formId") @Optional val formId: String? = null,
    @SerialName("id") @Optional val id: String? = null,
    @SerialName("landingPageId") @Optional val landingPageId: String? = null,
    @SerialName("leadBucketIds") @Optional val leadBucketIds: List<String>? = null,
    @SerialName("name") @Optional val name: String? = null,
    @SerialName("properties") @Optional val properties: Any? = null,
    @SerialName("ready") @Optional val ready: Boolean? = null,
    @SerialName("type") @Optional val type: CampaignLandingPageNodeDTO.Type? = null
) {

    /**
    * 
    * Values: WEBFORM,LANDINGPAGE,SURVEY,LINKCLICK,SCORE,PURCHASE,QUOTE,WEBSITETRIGGER,INTERNALFORM,TASK,STAGEMOVE,NOTE,TAG,GROSOCIAL,TWITTERFORM,API,WORDPRESS,NEWLANDINGPAGE
    */
    @Serializable(with = Type.Serializer::class)
    enum class Type(val value: String){
    
        WEBFORM("WebForm"),
    
        LANDINGPAGE("LandingPage"),
    
        SURVEY("Survey"),
    
        LINKCLICK("LinkClick"),
    
        SCORE("Score"),
    
        PURCHASE("Purchase"),
    
        QUOTE("Quote"),
    
        WEBSITETRIGGER("WebsiteTrigger"),
    
        INTERNALFORM("InternalForm"),
    
        TASK("Task"),
    
        STAGEMOVE("StageMove"),
    
        NOTE("Note"),
    
        TAG("Tag"),
    
        GROSOCIAL("GroSocial"),
    
        TWITTERFORM("TwitterForm"),
    
        API("API"),
    
        WORDPRESS("WordPress"),
    
        NEWLANDINGPAGE("NewLandingPage");
    

      class Serializer: EnumStringSerializer<Type>(Type::class)

      override fun toString(): String = value.toString()
    }

}

