/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
*
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 *
 * @param address
 * @param company_name
 * @param custom_fields
 * @param email_address
 * @param email_opted_in
 * @param email_status
 * @param fax_number
 * @param id
 * @param notes
 * @param phone_number
 * @param website
 */
@Serializable
data class Company (
    @SerialName("address") @Optional val address: CompanyAddress? = null,
    @SerialName("company_name") @Optional val companyName: String? = null,
    @SerialName("custom_fields") @Optional val customFields: List<CustomFieldValue>? = null,
    @SerialName("email_address") @Optional val emailAddress: String? = null,
    @SerialName("email_opted_in") @Optional val emailOptedIn: Boolean? = null,
    @SerialName("email_status") @Optional val emailStatus: Company.EmailStatus? = null,
    @SerialName("fax_number") @Optional val faxNumber: CompanyFaxNumber? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("notes") @Optional val notes: String? = null,
    @SerialName("phone_number") @Optional val phoneNumber: CompanyPhoneNumber? = null,
    @SerialName("website") @Optional val website: String? = null
) {

    /**
    *
    * Values: UNENGAGEDMARKETABLE,SINGLEOPTIN,DOUBLEOPTIN,CONFIRMED,UNENGAGEDNONMARKETABLE,NONMARKETABLE,LOCKDOWN,BOUNCE,HARDBOUNCE,MANUAL,ADMIN,SYSTEM,LISTUNSUBSCRIBE,FEEDBACK,SPAM,INVALID
    */
    @Serializable(with = EmailStatus.Serializer::class)
    enum class EmailStatus(val value: String){

        UNENGAGEDMARKETABLE("UnengagedMarketable"),

        SINGLEOPTIN("SingleOptIn"),

        DOUBLEOPTIN("DoubleOptin"),

        CONFIRMED("Confirmed"),

        UNENGAGEDNONMARKETABLE("UnengagedNonMarketable"),

        NONMARKETABLE("NonMarketable"),

        LOCKDOWN("Lockdown"),

        BOUNCE("Bounce"),

        HARDBOUNCE("HardBounce"),

        MANUAL("Manual"),

        ADMIN("Admin"),

        SYSTEM("System"),

        LISTUNSUBSCRIBE("ListUnsubscribe"),

        FEEDBACK("Feedback"),

        SPAM("Spam"),

        INVALID("Invalid");


      class Serializer: EnumStringSerializer<EmailStatus>(EmailStatus::class)

      override fun toString(): String = value.toString()
    }

}

