/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param card_number 
 * @param card_type 
 * @param id 
 * @param validation_status 
 */
@Serializable
data class ContactCreditCard (
    @SerialName("card_number") @Optional val cardNumber: String? = null,
    @SerialName("card_type") @Optional val cardType: String? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("validation_status") @Optional val validationStatus: String? = null
) {

}

