/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.CategoryReference

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param category The tag category reference
 * @param description The tag description
 * @param name The tag name
 */
@Serializable
data class CreateTag (
    /* The tag name */
    @SerialName("name") val name: String,
    /* The tag category reference */
    @SerialName("category") @Optional val category: CategoryReference? = null,
    /* The tag description */
    @SerialName("description") @Optional val description: String? = null
) {

}

