/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.ContactAddress

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param address 
 * @param card_type 
 * @param contact_id 
 * @param email_address 
 * @param expiration_month 
 * @param expiration_year 
 * @param id 
 * @param maestro_issue_number 
 * @param maestro_start_date_month 
 * @param maestro_start_date_year 
 * @param name_on_card 
 * @param validation_message 
 * @param validation_status 
 */
@Serializable
data class CreditCardAdded (
    @SerialName("address") @Optional val address: ContactAddress? = null,
    @SerialName("card_type") @Optional val cardType: String? = null,
    @SerialName("contact_id") @Optional val contactId: Long? = null,
    @SerialName("email_address") @Optional val emailAddress: String? = null,
    @SerialName("expiration_month") @Optional val expirationMonth: String? = null,
    @SerialName("expiration_year") @Optional val expirationYear: String? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("maestro_issue_number") @Optional val maestroIssueNumber: String? = null,
    @SerialName("maestro_start_date_month") @Optional val maestroStartDateMonth: String? = null,
    @SerialName("maestro_start_date_year") @Optional val maestroStartDateYear: String? = null,
    @SerialName("name_on_card") @Optional val nameOnCard: String? = null,
    @SerialName("validation_message") @Optional val validationMessage: String? = null,
    @SerialName("validation_status") @Optional val validationStatus: String? = null
) {

}

