/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param email 
 * @param field 
 */
@Serializable
data class EmailAddress (
    @SerialName("email") @Optional val email: String? = null,
    @SerialName("field") @Optional val field: EmailAddress.Field? = null
) {

    /**
    * 
    * Values: EMAIL1,EMAIL2,EMAIL3
    */
    @Serializable(with = Field.Serializer::class)
    enum class Field(val value: String){
    
        EMAIL1("EMAIL1"),
    
        EMAIL2("EMAIL2"),
    
        EMAIL3("EMAIL3");
    

      class Serializer: EnumStringSerializer<Field>(Field::class)

      override fun toString(): String = value.toString()
    }

}

