/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param key 
 */
//@Serializable Not using right now
data class EntryLongCommastring_ (
    @SerialName("key") @Optional val key: EntryLongCommastring_.Key? = null
) {

    /**
    * 
    * Values: SUCCESS,DUPLICATE,CONTACT_NOT_FOUND,TAG_ID_NOT_FOUND,FAILURE,NO_PERMISSION
    */
    @Serializable(with = Key.Serializer::class)
    enum class Key(val value: String){
    
        SUCCESS("SUCCESS"),
    
        DUPLICATE("DUPLICATE"),
    
        CONTACT_NOT_FOUND("CONTACT_NOT_FOUND"),
    
        TAG_ID_NOT_FOUND("TAG_ID_NOT_FOUND"),
    
        FAILURE("FAILURE"),
    
        NO_PERMISSION("NO_PERMISSION");
    

      class Serializer: EnumStringSerializer<Key>(Key::class)

      override fun toString(): String = value.toString()
    }

}

