/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param field 
 * @param number 
 * @param type 
 */
@Serializable
data class FaxNumber (
    @SerialName("field") val field: FaxNumber.Field,
    @SerialName("number") @Optional val number: String? = null,
    @SerialName("type") @Optional val type: String? = null
) {

    /**
    * 
    * Values: FAX1,FAX2
    */
    @Serializable(with = Field.Serializer::class)
    enum class Field(val value: String){
    
        FAX1("FAX1"),
    
        FAX2("FAX2");
    

      class Serializer: EnumStringSerializer<Field>(Field::class)

      override fun toString(): String = value.toString()
    }

}

