/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param category 
 * @param contact_id 
 * @param created_by 
 * @param date_created 
 * @param download_url 
 * @param file_box_type 
 * @param file_name 
 * @param file_size 
 * @param id 
 * @param last_updated 
 * @param &#x60;public&#x60; 
 * @param remote_file_key 
 */
//@Serializable Not using right now
data class FileDescriptor (
    @SerialName("id") val id: Long,
    @SerialName("category") @Optional val category: FileDescriptor.Category? = null,
    @SerialName("contact_id") @Optional val contactId: Long? = null,
    @SerialName("created_by") @Optional val createdBy: Long? = null,
    @SerialName("date_created") @Optional val dateCreated: java.time.LocalDateTime? = null,
    @SerialName("download_url") @Optional val downloadUrl: String? = null,
    @SerialName("file_box_type") @Optional val fileBoxType: FileDescriptor.FileBoxType? = null,
    @SerialName("file_name") @Optional val fileName: String? = null,
    @SerialName("file_size") @Optional val fileSize: Long? = null,
    @SerialName("last_updated") @Optional val lastUpdated: java.time.LocalDateTime? = null,
    @SerialName("&#x60;public&#x60;") @Optional val `Public`: Boolean? = null,
    @SerialName("remote_file_key") @Optional val remoteFileKey: String? = null
) {

    /**
    * 
    * Values: ATTACHMENTS,CART,DOCUMENTS,HIDDEN,INVOICE,LOGO,TICKETS,WEBFORM,FUNNEL
    */
    @Serializable(with = Category.Serializer::class)
    enum class Category(val value: String){
    
        ATTACHMENTS("Attachments"),
    
        CART("Cart"),
    
        DOCUMENTS("Documents"),
    
        HIDDEN("Hidden"),
    
        INVOICE("Invoice"),
    
        LOGO("Logo"),
    
        TICKETS("Tickets"),
    
        WEBFORM("WebForm"),
    
        FUNNEL("Funnel");
    

      class Serializer: EnumStringSerializer<Category>(Category::class)

      override fun toString(): String = value.toString()
    }

    /**
    * 
    * Values: APPLICATION,IMAGE,FAX,ATTACHMENT,TICKET,CONTACT,DIGITALPRODUCT,IMPORT,HIDDEN,WEBFORM,STYLEDCART,RESAMPLEDIMAGE,TEMPLATETHUMBNAIL,FUNNEL,LOGOTHUMBNAIL
    */
    @Serializable(with = FileBoxType.Serializer::class)
    enum class FileBoxType(val value: String){
    
        APPLICATION("Application"),
    
        IMAGE("Image"),
    
        FAX("Fax"),
    
        ATTACHMENT("Attachment"),
    
        TICKET("Ticket"),
    
        CONTACT("Contact"),
    
        DIGITALPRODUCT("DigitalProduct"),
    
        IMPORT("Import"),
    
        HIDDEN("Hidden"),
    
        WEBFORM("WebForm"),
    
        STYLEDCART("StyledCart"),
    
        RESAMPLEDIMAGE("ReSampledImage"),
    
        TEMPLATETHUMBNAIL("TemplateThumbnail"),
    
        FUNNEL("Funnel"),
    
        LOGOTHUMBNAIL("LogoThumbnail");
    

      class Serializer: EnumStringSerializer<FileBoxType>(FileBoxType::class)

      override fun toString(): String = value.toString()
    }

}

