/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.FileDescriptor

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param count 
 * @param files 
 * @param next 
 * @param previous 
 */
//@Serializable Not using right now
data class FileList (
    @SerialName("count") @Optional val count: Int? = null,
    @SerialName("files") @Optional val files: List<FileDescriptor>? = null,
    @SerialName("next") @Optional val next: String? = null,
    @SerialName("previous") @Optional val previous: String? = null
) {

}

