/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param campaign_id 
 * @param goal_id 
 * @param message 
 * @param success 
 */
//@Serializable Not using right now
data class GoalEventResultDTO (
    @SerialName("campaign_id") @Optional val campaignId: Long? = null,
    @SerialName("goal_id") @Optional val goalId: Long? = null,
    @SerialName("message") @Optional val message: String? = null,
    @SerialName("success") @Optional val success: Boolean? = null
) {

}

