/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param family_name 
 * @param given_name 
 * @param user_id 
 */
//@Serializable Not using right now
data class NoteUser (
    @SerialName("family_name") @Optional val familyName: String? = null,
    @SerialName("given_name") @Optional val givenName: String? = null,
    @SerialName("user_id") @Optional val userId: Long? = null
) {

}

