/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.Product_

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param cost 
 * @param description 
 * @param discount 
 * @param id 
 * @param name 
 * @param notes 
 * @param price 
 * @param product 
 * @param quantity 
 * @param type 
 */
//@Serializable Not using right now
data class OrderItem (
    @SerialName("cost") @Optional val cost: Double? = null,
    @SerialName("description") @Optional val description: String? = null,
    @SerialName("discount") @Optional val discount: Double? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("name") @Optional val name: String? = null,
    @SerialName("notes") @Optional val notes: String? = null,
    @SerialName("price") @Optional val price: Double? = null,
    @SerialName("product") @Optional val product: Product_? = null,
    @SerialName("quantity") @Optional val quantity: Int? = null,
    @SerialName("type") @Optional val type: String? = null
) {

}

