/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.PaymentGateway

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param auto_charge 
 * @param credit_card_id 
 * @param days_between_payments 
 * @param initial_payment_amount 
 * @param initial_payment_date 
 * @param number_of_payments 
 * @param payment_gateway 
 * @param plan_start_date 
 */
@Serializable
data class PaymentPlan (
    @SerialName("days_between_payments") val daysBetweenPayments: Int,
    @SerialName("number_of_payments") val numberOfPayments: Int,
    @SerialName("plan_start_date") val planStartDate: java.time.LocalDateTime,
    @SerialName("auto_charge") @Optional val autoCharge: Boolean? = null,
    @SerialName("credit_card_id") @Optional val creditCardId: Long? = null,
    @SerialName("initial_payment_amount") @Optional val initialPaymentAmount: Double? = null,
    @SerialName("initial_payment_date") @Optional val initialPaymentDate: java.time.LocalDateTime? = null,
    @SerialName("payment_gateway") @Optional val paymentGateway: PaymentGateway? = null
) {

}

