/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param extension 
 * @param field 
 * @param number 
 * @param type 
 */
//@Serializable Not using right now
data class PhoneNumber (
    @SerialName("field") val field: PhoneNumber.Field,
    @SerialName("extension") @Optional val extension: String? = null,
    @SerialName("number") @Optional val number: String? = null,
    @SerialName("type") @Optional val type: String? = null
) {

    /**
    * 
    * Values: PHONE1,PHONE2,PHONE3,PHONE4,PHONE5
    */
    @Serializable(with = Field.Serializer::class)
    enum class Field(val value: String){
    
        PHONE1("PHONE1"),
    
        PHONE2("PHONE2"),
    
        PHONE3("PHONE3"),
    
        PHONE4("PHONE4"),
    
        PHONE5("PHONE5");
    

      class Serializer: EnumStringSerializer<Field>(Field::class)

      override fun toString(): String = value.toString()
    }

}

