/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param active 
 * @param cycle_type 
 * @param frequency 
 * @param id 
 * @param number_of_cycles 
 * @param plan_price 
 * @param subscription_plan_index 
 * @param subscription_plan_name 
 * @param url 
 */
//@Serializable Not using right now
data class ProductSubscription (
    @SerialName("cycle_type") val cycleType: ProductSubscription.CycleType,
    @SerialName("id") val id: Long,
    @SerialName("plan_price") val planPrice: Double,
    @SerialName("active") @Optional val active: Boolean? = null,
    @SerialName("frequency") @Optional val frequency: Int? = null,
    @SerialName("number_of_cycles") @Optional val numberOfCycles: Int? = null,
    @SerialName("subscription_plan_index") @Optional val subscriptionPlanIndex: Int? = null,
    @SerialName("subscription_plan_name") @Optional val subscriptionPlanName: String? = null,
    @SerialName("url") @Optional val url: String? = null
) {

    /**
    * 
    * Values: YEAR,MONTH,WEEK,DAY
    */
    @Serializable(with = CycleType.Serializer::class)
    enum class CycleType(val value: String){
    
        YEAR("YEAR"),
    
        MONTH("MONTH"),
    
        WEEK("WEEK"),
    
        DAY("DAY");
    

      class Serializer: EnumStringSerializer<CycleType>(CycleType::class)

      override fun toString(): String = value.toString()
    }

}

