/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.ProductOption
import io.mverse.client.infusionsoft.models.SubscriptionPlan_

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param id 
 * @param product_desc 
 * @param product_name 
 * @param product_options 
 * @param product_price 
 * @param product_short_desc 
 * @param sku 
 * @param status 
 * @param sub_category_id 
 * @param subscription_only 
 * @param subscription_plans 
 * @param url 
 */
@Serializable
data class Product_ (
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("product_desc") @Optional val productDesc: String? = null,
    @SerialName("product_name") @Optional val productName: String? = null,
    @SerialName("product_options") @Optional val productOptions: List<ProductOption>? = null,
    @SerialName("product_price") @Optional val productPrice: Double? = null,
    @SerialName("product_short_desc") @Optional val productShortDesc: String? = null,
    @SerialName("sku") @Optional val sku: String? = null,
    @SerialName("status") @Optional val status: Int? = null,
    @SerialName("sub_category_id") @Optional val subCategoryId: Long? = null,
    @SerialName("subscription_only") @Optional val subscriptionOnly: Boolean? = null,
    @SerialName("subscription_plans") @Optional val subscriptionPlans: List<SubscriptionPlan_>? = null,
    @SerialName("url") @Optional val url: String? = null
) {

}

