/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param id 
 * @param linked_contact_id 
 * @param relationship_type_id 
 */
@Serializable
data class Relationship (
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("linked_contact_id") @Optional val linkedContactId: Long? = null,
    @SerialName("relationship_type_id") @Optional val relationshipTypeId: Long? = null
) {

}

