/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
*
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 *
 * @param address
 * @param company_name
 * @param created_by
 * @param date_created
 * @param email_address
 * @param family_name
 * @param fax_numbers
 * @param given_name
 * @param global_user_id
 * @param id
 * @param infusionsoft_id
 * @param job_title
 * @param last_updated
 * @param last_updated_by
 * @param middle_name
 * @param partner
 * @param phone_numbers
 * @param preferred_name
 * @param status
 * @param time_zone
 * @param website
 */
@Serializable
data class RestUser (
    @SerialName("id") val id: Long,
    @SerialName("address") @Optional val address: Address? = null,
    @SerialName("company_name") @Optional val companyName: String? = null,
    @SerialName("created_by") @Optional val createdBy: Long? = null,
    @SerialName("date_created") @Optional val dateCreated: java.time.LocalDateTime? = null,
    @SerialName("email_address") @Optional val emailAddress: String? = null,
    @SerialName("family_name") @Optional val familyName: String? = null,
    @SerialName("fax_numbers") @Optional val faxNumbers: List<FaxNumber>? = null,
    @SerialName("given_name") @Optional val givenName: String? = null,
    @SerialName("global_user_id") @Optional val globalUserId: Long? = null,
    @SerialName("infusionsoft_id") @Optional val infusionsoftId: String? = null,
    @SerialName("job_title") @Optional val jobTitle: String? = null,
    @SerialName("last_updated") @Optional val lastUpdated: java.time.LocalDateTime? = null,
    @SerialName("last_updated_by") @Optional val lastUpdatedBy: Long? = null,
    @SerialName("middle_name") @Optional val middleName: String? = null,
    @SerialName("partner") @Optional val partner: Boolean? = null,
    @SerialName("phone_numbers") @Optional val phoneNumbers: List<PhoneNumber>? = null,
    @SerialName("preferred_name") @Optional val preferredName: String? = null,
    @SerialName("status") @Optional val status: RestUser.Status? = null,
    @SerialName("time_zone") @Optional val timeZone: String? = null,
    @SerialName("website") @Optional val website: String? = null
) {

    /**
    *
    * Values: ACTIVE,INVITED,INACTIVE
    */
    @Serializable(with = Status.Serializer::class)
    enum class Status(val value: String){

        ACTIVE("Active"),

        INVITED("Invited"),

        INACTIVE("Inactive");


      class Serializer: EnumStringSerializer<Status>(Status::class)

      override fun toString(): String = value.toString()
    }

}

