/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.72014
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.Merchant

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param default_merchant_account 
 * @param merchant_accounts 
 */
@Serializable
data class RestMerchantAccountResponse (
    @SerialName("default_merchant_account") @Optional val defaultMerchantAccount: Long? = null,
    @SerialName("merchant_accounts") @Optional val merchantAccounts: List<Merchant>? = null
) {

}

