/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.HistoricalCounts
import io.mverse.client.infusionsoft.models.SequencePath

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param active_contact_count 
 * @param active_contact_count_completed 
 * @param historical_contact_count 
 * @param id 
 * @param name 
 * @param paths 
 */
//@Serializable Not using right now
data class Sequence (
    @SerialName("active_contact_count") @Optional val activeContactCount: Int? = null,
    @SerialName("active_contact_count_completed") @Optional val activeContactCountCompleted: Int? = null,
    @SerialName("historical_contact_count") @Optional val historicalContactCount: HistoricalCounts? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("name") @Optional val name: String? = null,
    @SerialName("paths") @Optional val paths: List<SequencePath>? = null
) {

}

