/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.CheckListItemDetails

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param check_list_items 
 * @param probability 
 * @param stage_order 
 * @param target_num_days 
 */
//@Serializable Not using right now
data class StageDetails (
    @SerialName("check_list_items") @Optional val checkListItems: List<CheckListItemDetails>? = null,
    @SerialName("probability") @Optional val probability: Int? = null,
    @SerialName("stage_order") @Optional val stageOrder: Int? = null,
    @SerialName("target_num_days") @Optional val targetNumDays: Int? = null
) {

}

