/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


import io.mverse.client.infusionsoft.infrastructure.EnumStringSerializer
/**
 * 
 * @param active 
 * @param auto_charge 
 * @param billing_amount 
 * @param billing_cycle 
 * @param billing_frequency 
 * @param contact_id 
 * @param credit_card_id 
 * @param end_date 
 * @param id 
 * @param next_bill_date 
 * @param payment_gateway_id 
 * @param product_id 
 * @param quantity 
 * @param start_date 
 * @param subscription_plan_id 
 * @param use_default_payment_gateway 
 */
//@Serializable Not using right now
data class Subscription (
    @SerialName("active") @Optional val active: Boolean? = null,
    @SerialName("auto_charge") @Optional val autoCharge: Boolean? = null,
    @SerialName("billing_amount") @Optional val billingAmount: Double? = null,
    @SerialName("billing_cycle") @Optional val billingCycle: Subscription.BillingCycle? = null,
    @SerialName("billing_frequency") @Optional val billingFrequency: Int? = null,
    @SerialName("contact_id") @Optional val contactId: Long? = null,
    @SerialName("credit_card_id") @Optional val creditCardId: Long? = null,
    @SerialName("end_date") @Optional val endDate: java.time.LocalDateTime? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("next_bill_date") @Optional val nextBillDate: java.time.LocalDateTime? = null,
    @SerialName("payment_gateway_id") @Optional val paymentGatewayId: Long? = null,
    @SerialName("product_id") @Optional val productId: Long? = null,
    @SerialName("quantity") @Optional val quantity: Long? = null,
    @SerialName("start_date") @Optional val startDate: java.time.LocalDateTime? = null,
    @SerialName("subscription_plan_id") @Optional val subscriptionPlanId: Long? = null,
    @SerialName("use_default_payment_gateway") @Optional val useDefaultPaymentGateway: Boolean? = null
) {

    /**
    * 
    * Values: YEAR,MONTH,WEEK,DAY
    */
    @Serializable(with = BillingCycle.Serializer::class)
    enum class BillingCycle(val value: String){
    
        YEAR("YEAR"),
    
        MONTH("MONTH"),
    
        WEEK("WEEK"),
    
        DAY("DAY");
    

      class Serializer: EnumStringSerializer<BillingCycle>(BillingCycle::class)

      override fun toString(): String = value.toString()
    }

}

