/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models


import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param description The category description
 * @param id The id for the tag category
 * @param name The category name
 */
//@Serializable Not using right now
data class TagCategory (
    /* The id for the tag category */
    @SerialName("id") val id: Long,
    /* The category name */
    @SerialName("name") val name: String,
    /* The category description */
    @SerialName("description") @Optional val description: String? = null
) {

}

