/**
* Infusionsoft REST API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.70.0.78606
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.mverse.client.infusionsoft.models

import io.mverse.client.infusionsoft.models.Order

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * 
 * @param amount 
 * @param collection_method 
 * @param contact_id 
 * @param currency 
 * @param errors 
 * @param gateway 
 * @param gateway_account_name 
 * @param id 
 * @param order_ids 
 * @param orders 
 * @param status 
 * @param test 
 * @param transaction_date 
 * @param type 
 */
//@Serializable Not using right now
data class Transaction (
    @SerialName("amount") @Optional val amount: Double? = null,
    @SerialName("collection_method") @Optional val collectionMethod: String? = null,
    @SerialName("contact_id") @Optional val contactId: Long? = null,
    @SerialName("currency") @Optional val currency: String? = null,
    @SerialName("errors") @Optional val errors: String? = null,
    @SerialName("gateway") @Optional val gateway: String? = null,
    @SerialName("gateway_account_name") @Optional val gatewayAccountName: String? = null,
    @SerialName("id") @Optional val id: Long? = null,
    @SerialName("order_ids") @Optional val orderIds: String? = null,
    @SerialName("orders") @Optional val orders: List<Order>? = null,
    @SerialName("status") @Optional val status: String? = null,
    @SerialName("test") @Optional val test: Boolean? = null,
    @SerialName("transaction_date") @Optional val transactionDate: String? = null,
    @SerialName("type") @Optional val type: String? = null
) {

}

